### ISSUE TITLE
Discussion: Also use this in combination with Auto apply plugin

### ISSUE THREAD

**Issue by mlnl221** [Bunsly/JobSpy#10]
I found that the application

https://addons.mozilla.org/en-US/firefox/addon/simplify-jobs/

can easily auto apply for you on the compnays website from the linkedin links. Awesome pluging when used with yours as well.

**Comment by cullenwatson** [comment]
Yea they're good. My brother made one too, [speedyapply](https://speedyapply.com) which can do the same sites, might open source it soon.
