### ISSUE TITLE
Feature: Time-based filtering

### ISSUE THREAD

**Issue by talperetz** [Bunsly/JobSpy#100]
I love what you're building. 
Is it possible to add a filter to search for _recent_ jobs e.g `from` field that accepts a datetime and uses it as a cutoff?

Alternatively, if we can order by `date_posted` that would be helpful as well. 
I'm not sure how the jobs are ordered now, seems pretty random.

I currently do this manually, but filtering before we get the results would reduce the likelihood of getting blocked, and latency:
`jobs.sort_values(by='date_posted', ascending=False)`

**Comment by VitaminB16** [comment]
Made a pull request for this feature: https://github.com/Bunsly/JobSpy/pull/103
