### ISSUE TITLE
All Indeed Jobs have null Descriptions

### ISSUE THREAD

**Issue by andrekeiser** [Bunsly/JobSpy#101]
Used the simple example from the README and all Indeed results return a null description.  (Also tried a few others)

LinkedIn, Zip, and Glassdoor all seem to be working fine

**Comment by cullenwatson** [comment]
full_decription=True

**Comment by andrekeiser** [comment]
Ah thank you!  Glanced over that optional field, but didn't think False meant No description (and it worked for LinkedIn)

**Comment by cullenwatson** [comment]
Fetches by default now
