### ISSUE TITLE
Does JobSpy software work?

### ISSUE THREAD

**Issue by DavidPerea** [Bunsly/JobSpy#102]
Does JobSpy software work?
https://www.bunsly.com/demo/jobspy

I'm trying to download blockain jobs but it gives me an empty excel or csv. What is the error?

**Comment by cullenwatson** [comment]
the python package is good. I would use that, the site was kinda a quick way to show it works but needs updating.

**Comment by cullenwatson** [comment]
working now, but I'd still recommend the python package as it only returns the first page of results
