### ISSUE TITLE
Job URL and Company Image

### ISSUE THREAD

**Issue by calvinomiguel** [Bunsly/JobSpy#109]
It would be cool if we could get the company image and the external job URL and not the linkedin, indeed, glassdoor one. e.g. if it's an Apple job ad on linkedin, the URL should be the one that redirects the user directly to Apple's job page.

**Comment by cullenwatson** [comment]
Yea not a bad idea. Only problem is linkedin loads the links through javascript and is not visible in the HTML. So we'd have to think about how we'd go about fetching the URLs.

<img width="1174" alt="image" src="https://github.com/Bunsly/JobSpy/assets/78247585/356a87ca-9cd8-4dc6-b109-9592973d2300">

**Comment by mohammadpatel** [comment]
can we get  job directly apply url and logo?
