### ISSUE TITLE
Scraping companies websites of LinkedIn

### ISSUE THREAD

**Issue by diegotrasobares** [Bunsly/JobSpy#111]
Hey! Love the library!!
Not an actual issue, more like a question.
Is there a way to get the websites url of the companies instead of the LinkedIn profile url?
Like all companies have their own website attach to their LinkedIn profile, so that is actually what I want.
Thanks in advance!!

**Comment by C-Nubela** [comment]
Hey there @diegotrasobares 

I work at Proxycurl, a B2B data provider and API, and while I'm not affiliated with this project, you could use our Company Lookup Endpoint to look up a given company's website with their LinkedIn URL.

[Give this documentation here a read](https://nubela.co/proxycurl/docs#company-api-company-lookup-endpoint?utm_campaign=content_amplification&utm_source=reddit&utm_medium=social&utm_content=comments). I think you might find it valuable.

**Comment by ZacharyHampton** [comment]
Use clay or some other service to enrich your data.
