### ISSUE TITLE
Suggestion : Add a scrapper for websites using workday (workday.com)

### ISSUE THREAD

**Issue by Erim32** [Bunsly/JobSpy#114]
Idea, create a scraper or an extendable scrapper interface to scrap websites using workday solution for job posting.

**Comment by cullenwatson** [comment]
I have it created but we would need all the workday links. You have a list to provide to the bot?

**Comment by cullenwatson** [comment]
yea, not a bad idea. just wondering if there's much demand. will leave it open to see

**Comment by Erim32** [comment]
Yes, probably depends on whether users want to spy on job boards by domain or by company. Especially if you've already created it, it would add extra functionality and new use cases to JobSpy.
 
To simplify the integration, you could potentially create a branch with the code you've already created and I'll look at how to modify it to make it flexible, then propose a PR.
