### ISSUE TITLE
Jobs' description is not scraped

### ISSUE THREAD

**Issue by mingolladaniele** [Bunsly/JobSpy#121]
Hi! First of all, this tool is fantastic so thanks to all the people who are working on it.

I'm not able to get the description of the jobs. I noticed that also if i set the `full_description` argument to `True`, the column description of the returned dataset containing all the scraped jobs will contains the value `None` only. Am I doing something wrong?

Thanks for the support! :D
I'm using the code below:
```
scraped_jobs_df = scrape_jobs(
        site_name=["linkedin"],
        search_term="Data Analyst",
        location="London",
        results_wanted=50,
        full_description=True,
        proxy=proxy
        # country_indeed="USA",  # only needed for indeed / glassdoor
    )
```

**Comment by cullenwatson** [comment]
try linkedin_fetch_description=True

let met know if that works

**Comment by mingolladaniele** [comment]
Thanks for your answer, now it's working! 😊
