### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vj-sananda** [Bunsly/JobSpy#131]
Running python 3.10.12 on a Mac.
No errors on pip install -U python-jobspy

(py10)  (main) JobSpy $ python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jobspy
Segmentation fault: 11

Any ideas ?

**Comment by cullenwatson** [comment]
MacOS Catalina?

**Comment by vj-sananda** [comment]
Yup, works on Linux and even windows 11

**Comment by cullenwatson** [comment]
yea, unfortunately it's an issue due to a dependency not supporting Catalina

https://github.com/bogdanfinn/tls-client/issues/16
