### ISSUE TITLE
can search_term allows more key words as input

### ISSUE THREAD

**Issue by paramgunturi** [Bunsly/JobSpy#137]
Hi 
thank you for this very helpful code, I want to check if there is a plan to allow multiple search_term (like this: site_name: str | list[str] | Site | list[Site] | None = None,) instead of one(current implementation).

**Comment by cullenwatson** [comment]
there's not currently a plan. currently use for loop in calling code. is this ciritical?

**Comment by paramgunturi** [comment]
while searching for jobs on a particular technology, there will be multiple keywords right now I am only allowed to give one keyword it multiple keywords are allowed I can get all jobs in one sheet instead of multiple.

**Comment by ZacharyHampton** [comment]
Simply, merge using futures & as_completed from concurrent.futures. Adding this feature will just add complexity to the project in case of exceptions, supporting multiple sites in one call is already crossing the line a bit.
