### ISSUE TITLE
Please help with scraping linkedin job_url_direct

### ISSUE THREAD

**Issue by amanag13** [Bunsly/JobSpy#142]

**Comment by cullenwatson** [comment]
```bash
pip install -U python-jobspy
```

```python
import csv
from jobspy import scrape_jobs

jobs = scrape_jobs(
    site_name="linkedin",
    search_term="software engineer",
    location="Bangalore",
    results_wanted=20,
    linkedin_fetch_description=True
)
print(f"Found {len(jobs)} jobs")
print(jobs.head())
jobs.to_csv("jobs.csv", quoting=csv.QUOTE_NONNUMERIC, escapechar="\\", index=False) # to_xlsx
```

**Comment by amanag13** [comment]
"job_url_direct" is returning null for linkedin

**Comment by cullenwatson** [comment]
can yo share your code?

**Comment by amanag13** [comment]
Version: 1.1.51

jobs = scrape_jobs(
    site_name=["linkedin"],
    search_term=x,
    location="India",
    results_wanted=100,
    linkedin_fetch_description=True,
    description_format="html",
    job_url_direct=True,
    hours_old=24, # (only Linkedin/Indeed is hour specific, others round up to days old)
    country_indeed='US'  # only needed for indeed / glassdoor
    )

**Comment by cullenwatson** [comment]
current version is 1.1.52

**Comment by amanag13** [comment]
Thanks for prompt response. Appreciate it!
