### ISSUE TITLE
Improve LinkedIn scraper robustness

### ISSUE THREAD

**Issue by lluissalord** [Bunsly/JobSpy#144]
Reviewing some posts about scraping LinkedIn Jobs I found that the same data extracted from `https://www.linkedin.com/jobs/view/<JOB_ID>` is coming from `https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/<JOB_ID>`. 

Then, it makes me think that maybe using this second URL could make the scraper more robust to not get blocked by LinkedIn. I haven't tried, but it could be interesting to make a stress test to see if it has better behavior.

**Comment by cullenwatson** [comment]
Should be able test just call the each endpoint x times and see which gets 429 first. However, we get 429 quickly with jobs page search and it's same api format as that endpoint
