### ISSUE TITLE
Unable to scrape jobs from multiple locations

### ISSUE THREAD

**Issue by Sandip-Tiwari-435** [Bunsly/JobSpy#149]
The feature where i can be able to extract jobs belonging to locations from lets say **Dallas, TX and Hollywood, CA** together. Is it possible? If yes, how to define it because the location argument doesn't take a list but a string. It would be helpful if this feature was added if not already present. I have tried using **comma separated cities in the location argument**. But it doesn't seem to work for some reason I can't find why

**Comment by cullenwatson** [comment]
Yes concat data frames. Gpt can help
