### ISSUE TITLE
Fetch Job function from LinkedIn

### ISSUE THREAD

**Issue by amanag13** [Bunsly/JobSpy#153]
Is it possible to fetch job function from LinkedIn response? For example, Design, Marketing, Engineering etc

<img width="534" alt="Screenshot 2024-05-24 at 2 14 15 PM" src="https://github.com/Bunsly/JobSpy/assets/29747515/1c4c0ddb-b333-42aa-87c4-62627ba0dc4d">

**Comment by cullenwatson** [comment]
* #160
