### ISSUE TITLE
Doubt on how legal is this for scraping jobs on linkedin 

### ISSUE THREAD

**Issue by Anurag-Varma** [Bunsly/JobSpy#178]
Hi,

Can any member of this repo comment on how legal is using of this repo to scrap jobs from linkedin legal ?

Does it violate any laws cuz its publicly available data.

Scraping violates linkedin tos. But still can this be done ?

I wanted to know the details before i start my project on it using this library.

**Comment by rasmus86** [comment]
Is LinkedIn scraping legal? 
Scraping LinkedIn data without permission violates LinkedIn's terms of service and can lead to legal consequences.
What are the benefits of LinkedIn scraping? 
Benefits include market research, lead generation, job market analysis, and competitive intelligence.
What are the risks of LinkedIn scraping? 
Risks include legal action, ethical concerns, and technical challenges related to data accuracy and anti-scraping measures.
Source:
https://www.linkedin.com/pulse/what-scraping-linkedin-radhika-rajput-h3alc/

**Comment by Anurag-Varma** [comment]
But we are not logging in the website and so not agreeing to TOS.

So just want to know if this github repo is ok to be used in my project

**Comment by ZacharyHampton** [comment]
Yes, we're not logging in and only scraping public data. This is legal to use.
