### ISSUE TITLE
Is indeed working as expected? 

### ISSUE THREAD

**Issue by haowjern** [Bunsly/JobSpy#192]
Hi, 

For Indeed, when I search for jobs = "Software Engineer" in Malaysia I get these 5 job titles

1. System and Server Engineer
2. Product Engineer
3. Product Reliability Engineer
4. Software Engineer
5. Senior Enterprise Technology Engineer

If I search for Dallas, US, I get this
1. Manager, Software Development & Engineering
2. Sr. Specialist, Software Development & Engineeing
3. Senior Software Engineer, Front End
4. Software Development Engineer III
5. Senior Principal Firmware Lead Engineer (Onsite)

This seems a bit different from their website, and I would expect more software engineer related roles - any reasons why or is this expected?

**Comment by cullenwatson** [comment]
put your search term in quotes

jobs = scrape_jobs(
    site_name="indeed",
    search_term='"software engineer"',
    results_wanted=30,
    country_indeed="malaysia"
)
