### ISSUE TITLE
Incomplete ZipRecruiter Job Descriptions 

### ISSUE THREAD

**Issue by delvinso** [Bunsly/JobSpy#195]
I'm on version 1.1.65, these job descriptions are short and end in `...`.

**Comment by cullenwatson** [comment]
seems full for my searches. what search gives you ...

**Comment by delvinso** [comment]
i think my ip may have been blocked/restricted. the same search I use on a vm results in the truncated job descriptions but not on my local machine - either way doesn't look like an issue on your end.
