### ISSUE TITLE
LinkedIn Location Error with "Turkey" – Invalid Country String: 'türkiye'

### ISSUE THREAD

**Issue by pelinkaynarca** [Bunsly/JobSpy#199]
When the location parameter is set to "turkey", I receive the following exception:

`jobspy.scrapers.exceptions.LinkedInException: Invalid country string: 'türkiye'. Valid countries are: argentina, australia, austria, bahrain, belgium, brazil, canada, chile, china, colombia, costa rica, czech republic,czechia, denmark, ecuador, egypt, finland, france, germany, greece, hong kong, hungary, india, indonesia, ireland, israel, italy, japan, kuwait, luxembourg, malaysia, malta, mexico, morocco, netherlands, new zealand, nigeria, norway, oman, pakistan, panama, peru, philippines, poland, portugal, qatar, romania, saudi arabia, singapore, south africa, south korea, spain, sweden, switzerland, taiwan, thailand, turkey, ukraine, united arab emirates, uk,united kingdom, usa,us,united states, uruguay, venezuela, vietnam, usa/ca, worldwide`

The issue is specific to LinkedIn, as searches for "turkey" work fine with Glassdoor and Indeed. "Turkey" seems to be automatically transformed to "türkiye" with LinkedIn searching. When searching manually on LinkedIn, "türkiye" is the correct location to search for jobs in the country. If you search "turkey", LinkedIn defaults the search to "Turkey, North Carolina, United States", not the country.

**Comment by cullenwatson** [comment]
oh yea good catch. 

`pip install -U python-jobspy` to 1.1.68, should work
