### ISSUE TITLE
Tests are installed with the package

### ISSUE THREAD

**Issue by olzhasar** [Bunsly/JobSpy#207]
Hi,
Thank you for the great package.

There is a subtle issue when trying to integrate `JobSpy` to an existing project.
The problem is that `tests` are being exposed as a package alongside the actual library which leads to problems when there is already a `tests` package in a project.
e.g.:
```
from tests import something
```
It will try to import from JobSpy tests instead of the project.tests

Potential solutions:
- Extract tests from the src folder
- Exclude tests from the poetry build

**Comment by cullenwatson** [comment]
good catch
