### ISSUE TITLE
Possible misuse of threading in the `indeed` scraper

### ISSUE THREAD

**Issue by olzhasar** [Bunsly/JobSpy#208]
There is the following code in `jobspy.scrapers.indeed.__init__.py`:

```py3
        with ThreadPoolExecutor(max_workers=self.num_workers) as executor:
            job_results: list[Future] = [
                executor.submit(self._process_job, job["job"]) for job in jobs
            ]
```

2 potential problems here:
- `_process_job` method does not seem to contain any IO logic, so using threading is likely an unnecessary overhead there
- `_process_job` adds elements to the `seen_urls` set, which is not thread-safe, so this can lead to inconsistent state

My suggestion is to get rid of the ThreadPoolExecutor in that part of the code

**Comment by cullenwatson** [comment]
true we should use aiohttp
