### ISSUE TITLE
Google integration

### ISSUE THREAD

**Issue by malys** [Bunsly/JobSpy#215]
Hi,
the new Google integration is working only for countries using english language.
To forge google search queries, you forge then using statics english part of sentences (ex: "in the last week") but google search use translation in local language.
ex:
In spain en las ultimas semanas
In french la dernière semaine

Could create parameters to override statics values like "jobs, since yesterday, ....)?

Many thanks for your work.

**Comment by cullenwatson** [comment]
ok thanks for the feedback. ill fix

**Comment by cullenwatson** [comment]
maybe you pass a language param? like language=spanish?

**Comment by cullenwatson** [comment]
okay i just added a generic and it'll override the other params. so just put everything in here

google_search_term="Trabajos de ingeniero de software Barcelona, España",

**Comment by ThomasAlbrt** [comment]
Just to add to this, results being displayed is not tied to the IP address.

However only jobs from specific countries are being displayed now. 
For example results from the Nordics are no longer supported.

So far it seems only those countries are supported:

dz, ao, ag, ar, at, bs, bh, bd, bz, bj, bo, bw, br, bf, bi, cm, ca, cv, ky, cf, cl, co, cg, cd, cr, dk, dj, dm, do, ec, eg, sv, et, fk, fr, ga, gm, de, gh, gr, gp, gt, gy, hn, hk, in, id, iq, it, jm, jp, jo, ke, kw, lb, ls, ly, mw, my, mu, mx, ms, ma, mz, na, nl, ni, ng, om, pk, ps, pa, py, pe, ph, pt, pr, qa, re, ru, rw, sh, vc, st, sa, sn, sc, sl, sg, so, za, es, lk, sr, ch, tw, tz, th, tg, tt, tn, ug, ae, uk, gb, us, uy, ve, vn, vg, vi, zm, zw
