### ISSUE TITLE
Indeed Search Inaccurate

### ISSUE THREAD

**Issue by sulynajimsj** [Bunsly/JobSpy#217]
Hey,

I have been trying the indeed search and it seems inaccurate compared to when I try it on indeed's site? How is the data being scraped, is it by date posted or relevance? Also can we make a change so that it looks at title mainly not just description, because I rarely get accurate results for indeed it's weird

**Comment by cullenwatson** [comment]
What's your search, paste it here so we can look into it

**Comment by cullenwatson** [comment]
i think this is more powerful than just searching the title tho. every keyword has to be present in the description or title that is in your search term.

use - to remove words, "" for exact match. so for this the description/title must include summer, java, 2025, software engineering intern, no tax, no marketing

search_term='"software engineering intern" summer java 2025 -tax -marketing'

**Comment by sulynajimsj** [comment]
Thanks @cullenwatson I do still think having an option to just search via title would be nice as a option for indeed because the results are super inaccurate for Software Engineering internship for example, I almost get none but when I search on indeed it gets it right.

**Comment by cullenwatson** [comment]
Every result for me is a hit. Whats your search

<img width="394" alt="image" src="https://github.com/user-attachments/assets/adfa534f-f915-4ec1-8f0e-3ee018b9cce0">

**Comment by sulynajimsj** [comment]
This is my search is yours to the US? Maybe thats the issue but still for indeed canada I get accurate results and using the scraper not rlly. This is my search



jobs = scrape_jobs(
            site_name=["indeed"],
            search_term="Software Engineering Intern",
            location='Canada',
            linkedin_fetch_description=True,
            results_wanted=50,
            country_indeed='canada'
        )

**Comment by sulynajimsj** [comment]
What was your search to get that?

**Comment by sulynajimsj** [comment]
was it indeed?

**Comment by cullenwatson** [comment]
yes, try

```py
jobs = scrape_jobs(
    site_name=["indeed"],
    search_term='"software developer intern" OR "software engineer intern"',
    location="Canada",
    results_wanted=50,
    radius=100,
    country_indeed='canada',
)
```

**Comment by sulynajimsj** [comment]
Nice! Was it the radius maybe the results are actually more accurate! Thank you
