### ISSUE TITLE
 KeyError: 'GOOGLE' when I try use google?

### ISSUE THREAD

**Issue by sulynajimsj** [Bunsly/JobSpy#218]
Hello,

When I try scrape jobs using the example given in the: I get a Key error for Google

import csv
from jobspy import scrape_jobs

jobs = scrape_jobs(
    site_name=["indeed", "linkedin", "zip_recruiter", "glassdoor", "google"],
    search_term="software engineer",
    google_search_term="software engineer jobs near San Francisco, CA since yesterday",
    location="San Francisco, CA",
    results_wanted=20,
    hours_old=72,
    country_indeed='USA',
    
    # linkedin_fetch_description=True # gets more info such as description, direct job url (slower)
    # proxies=["208.195.175.46:65095", "208.195.175.45:65095", "localhost"],
)
print(f"Found {len(jobs)} jobs")
print(jobs.head())
jobs.to_csv("jobs.csv", quoting=csv.QUOTE_NONNUMERIC, escapechar="\\", index=False) # to_excel

I don't think this happened before

**Comment by prajwal2431** [comment]
Is this issue still open I want to work on it?

**Comment by cullenwatson** [comment]
not getting this error. you might have an old version of the package
