### ISSUE TITLE
Switch Indeed to use their GraphQL API

### ISSUE THREAD

**Issue by cullenwatson** [Bunsly/JobSpy#59]

**Comment by LorenzoLaCorte** [comment]
Is this the reason why Indeed scraping doesn't work anymore? It raises an exception relative to JSON parsing..

**Comment by cullenwatson** [comment]
> Is this the reason why Indeed scraping doesn't work anymore? It raises an exception relative to JSON parsing..

It stopped working but my latest release fixed it.

**Comment by cullenwatson** [comment]
Needs bypass
![image](https://github.com/Bunsly/JobSpy/assets/78247585/408c4a62-df2c-485f-b76b-baf25c6d40a9)
