### ISSUE TITLE
ZipRecruiter Job Scraper returns 'NoneType' exception

### ISSUE THREAD

**Issue by KilovoIt** [Bunsly/JobSpy#65]
What I have:
Python 3.11, clean install
```
from jobspy import scrape_jobs

jobs = scrape_jobs(
    site_name=["indeed", "linkedin", "zip_recruiter"],
    search_term="software engineer",
    location="Dallas, TX",
    results_wanted=10,
    country_indeed="USA",  # only needed for indeed
)
print(f"Found {len(jobs)} jobs")
print(jobs.head())
jobs.to_csv("jobs.csv", index=False)  # / to_xlsx
```

When I try to run this, I get the following error:

`jobspy.scrapers.exceptions.ZipRecruiterException: 'NoneType' object is not iterable`
which points to:

```
line 90, in scrape
 jobs_on_page, continue_token = self.find_jobs_in_page(scraper_input, continue_token)
```
    
this method.
  
I tried to use different parameters for the search, seems like ZipRecruiter is not working with any of them.

**Comment by cullenwatson** [comment]
@KilovoIt should be good now
