### ISSUE TITLE
I can't install python-jobspy on my venv python3.12.1

### ISSUE THREAD

**Issue by pedrobarthrodrigues** [Bunsly/JobSpy#75]
I can't install python-jobspy on my venv python3.12.1.
I'm getting the
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
error. I've tried many different methods but it always comes back to this.

**Comment by ytalp17** [comment]
creating an environment with different python version could be an alternative solution

**Comment by ZacharyHampton** [comment]
Hey, try this out: https://stackoverflow.com/a/77364602

We only use Python 3.10 over here, so we hadn't ran into this issue.
