### ISSUE TITLE
Error in packages

### ISSUE THREAD

**Issue by solidagold** [Bunsly/JobSpy#76]
Image attached >> [image](https://github.com/Bunsly/JobSpy/assets/155430370/d9dfc91d-1842-4d98-9082-0be5a9d35a90)
I've been trying to download this package to no avail. The package is installed on my computer, but for some reason, this code doesn't run. Can I ask for help regarding this matter? Thank you.

**Comment by DanielOX** [comment]
@solidagold how many python versions are installed on your computer? try running the following `whereis python` command. You also need to verify which python interpreter is being used in pycharm. it might be the one where this package was not installed.

**Comment by solidagold** [comment]
I only had 3.8 and 3.10 installed - I removed the 3.8 one so the only python version left is 3.10, Furthermore, I checked the python interpreter part and it is running on 3.10. 

This is the error I got when I tried running the code >> 
![image](https://github.com/Bunsly/JobSpy/assets/155430370/e1e5cdf5-3c10-48e4-9582-52a9bf336c7b)

**Comment by DanielOX** [comment]
can you try installing the package with pip command. open a new terminal and type `python3.10 -m pip install python-jobspy`. after than close the pycharm and reopen it. let me know if that works for you.

**Comment by solidagold** [comment]
Is that a command that works for windows? It says it's not a recognized internal or external command.

**Comment by DanielOX** [comment]
Yes, it is windows compatible command. can you try with `python -m pip install python-jobspy`? this time without mentioning python's version

**Comment by solidagold** [comment]
It works now! Thanks so much. But I ran the code and there's no output. Does it take time for the code to run, or is this a potential error? Thanks.

**Comment by DanielOX** [comment]
There seems to be an error with glassdoor, try removing glassdoor from site_name array.

**Comment by DanielOX** [comment]
@solidagold let me know if it worked?

**Comment by DanielOX** [comment]
This issue can be closed. please assign this issue to me if possible.

cc: @ZacharyHampton

**Comment by solidagold** [comment]
Oh sorry, just received the notification now. I'll try it ASAP.

**Comment by solidagold** [comment]
Works now, thanks so much!
