### ISSUE TITLE
Taking 3-4 minutes per result on LinkedIn

### ISSUE THREAD

**Issue by kodyVS** [Bunsly/JobSpy#78]
All the other websites work great! However, when doing searches on Linkedin, it takes 3-4 minutes per result. Does anyone else have the same issue?

**Comment by cullenwatson** [comment]
try updating, should be 1 minute max for 100 results

**Comment by kodyVS** [comment]
Great, it's mostly working now. The only time it hangs now is if you set a job criteria that is too focused and doesn't have as many results as you specify in `results_wanted` 

For instance
```
jobs= scrape_jobs(
    site_name=["linkedin",],
    search_term="dancer on a boat",
    location="Ontario",
    country_indeed="canada",
    results_wanted=30
)
```

**Comment by cullenwatson** [comment]
ah nice catch, see if it's good now

**Comment by kodyVS** [comment]
It's working great now, thanks for updating.
