### ISSUE TITLE
improvement: Remove pandas dependency

### ISSUE THREAD

**Issue by pippinmole** [Bunsly/JobSpy#86]
Hi,

I'd like to set up a serverless function which runs every 15 minutes to scrape jobs and put them into a database. However, many serverless providers (like [DigitalOcean Functions](https://docs.digitalocean.com/products/functions/)) have [package size restrictions](https://docs.digitalocean.com/products/functions/details/limits/).

It looks like Pandas (which has a dependency of numpy) takes up at least 120MB. All to use `pd.DataFrame`.

I understand this is quite a big change, so I don't expect anything.

Thanks

**Comment by cullenwatson** [comment]
We use pandas because it's easy for the end user to export but can understand the size issue. Any reason for not using AWS Lambda which has 250MB limit?
