### ISSUE TITLE
Feature request: allow filtering linkedin job requests by linkedin company ID

### ISSUE THREAD

**Issue by arosier10** [Bunsly/JobSpy#90]
I have a list of company ID's that I search for jobs by, along with keyword and location. Would be nice to be able to pull this programatically.

**Comment by cullenwatson** [comment]
good idea. Added it, uses linkedin_company_ids parameter. e.g. linkedin_company_ids=[4456, 14336],

**Comment by IgorFreik** [comment]
An easy way to look up the linkedin_company_id for your company:
1. Go to LinkedIn job search
2. Select in the filters the company of interest
3. Look at the field f_C in the http address

E.g. here it is for Uber:
<img width="1026" alt="Screen Shot 2024-02-17 at 15 13 56" src="https://github.com/Bunsly/JobSpy/assets/87539984/f89d3882-7779-4085-9945-cf42299abc2e">

**Comment by cullenwatson** [comment]
Yes that's what we're doing in the code
